# Generated by Django 5.2.1 on 2025-10-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_coord', '0002_alter_place_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='request',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=256, unique=True, verbose_name='Адрес'),
        ),
    ]
