# Generated by Django 5.2.1 on 2025-10-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Принят'), ('PREPARING', 'Готовится'), ('DELIVERING', 'Передан курьеру'), ('DELIVERED', 'Доставлен')], db_index=True, default='ACCEPTED', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
