# Generated by Django 5.2.1 on 2025-10-11 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 10, 11, 13, 40, 24, 75149, tzinfo=datetime.timezone.utc), verbose_name='Звонок в'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 10, 11, 13, 40, 31, 551275, tzinfo=datetime.timezone.utc), verbose_name='Доставка в'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 10, 11, 13, 39, 41, 708699, tzinfo=datetime.timezone.utc), verbose_name='Зарегистрирован в'),
        ),
    ]
