# Generated by Django 5.2.1 on 2025-10-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
    ]
