# Generated by Django 5.2.1 on 2025-10-19 20:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_remove_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Мобильный номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Необработано'), ('ACCEPTED', 'Принят'), ('PREPARING', 'Готовится'), ('DELIVERING', 'Передан курьеру'), ('DELIVERED', 'Доставлен')], db_index=True, default='UNPROCESSED', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
